### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dectectable** [Qwakeactyl/Qwakeactyl#3]
[Qwakeactyl] Loaded Website on the port 9999
(node:223921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /root/Qwakeactyl/index.js:240:82
    at Layer.handle [as handle_request] (/root/Qwakeactyl/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:137:13)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/root/Qwakeactyl/node_modules/express/lib/router/route.js:112:3)
(node:223921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:223921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[WEBSITE] An error has occured on path /:
Error: ENOENT: no such file or directory, open './themes/Qwakeactyl/index.ejs'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync [as fileLoader] (fs.js:393:35)
    at fileLoader (/root/Qwakeactyl/node_modules/ejs/lib/ejs.js:291:18)
    at handleCache (/root/Qwakeactyl/node_modules/ejs/lib/ejs.js:231:16)
    at tryHandleCache (/root/Qwakeactyl/node_modules/ejs/lib/ejs.js:272:16)
    at Object.exports.renderFile (/root/Qwakeactyl/node_modules/ejs/lib/ejs.js:489:10)
    at /root/Qwakeactyl/api/pages.js:72:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './themes/Qwakeactyl/index.ejs'
}
(node:223921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /root/Qwakeactyl/index.js:240:82
    at Layer.handle [as handle_request] (/root/Qwakeactyl/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:137:13)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at next (/root/Qwakeactyl/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/root/Qwakeactyl/node_modules/express/lib/router/route.js:112:3)
(node:223921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

![image](https://user-images.githubusercontent.com/75132173/162631173-423bf54a-4443-4512-be98-19a9da3ccb18.png)

**Comment by Mansffer** [comment]
To resolve this issue:

> [WEBSITE] An error has occured on path /:
Error: ENOENT: no such file or directory, open './themes/Qwakeactyl/index.ejs'

Just rename the themes directory with the command below.

`mv theme themes`
