### ISSUE TITLE
Error: ENOENT: no such file or directory, open './themes/Qwakeactyl/index.ejs'

### ISSUE THREAD

**Issue by 3lmack** [Qwakeactyl/Qwakeactyl#6]
why

$ npm start

> qwakeactyl@0.4.5 start
> node .

[Qwakeactyl] Files loading...
[Qwakeactyl] Files loaded...
[Qwakeactyl] Settings loading...
[Qwakeactyl] Settings loaded...
[Qwakeactyl] Database loading...
[Qwakeactyl] Database loaded...
[Qwakeactyl] api's loading...
[Qwakeactyl] api's loaded...
[Qwakeactyl] Express addons loading...
[Qwakeactyl] Express addons loaded...
[Qwakeactyl] Season data loading...
[Qwakeactyl] Season data loaded...
[Qwakeactyl] Website loading...
==================================================
[Qwakeactyl] ©️ IC DEVELOPMENT:
 Links:
 [Github] https://github.com/Team-IC/Qwakeactyl
 [Discord] https://discord.gg/ic
==================================================
[Contributors]
 [Just a Kartik#6927
 ||**AshishOp.java**||#0666]
==================================================
(node:2672) Warning: Accessing non-existent property 'text' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[Qwakeactyl] Loaded Website on the port 8181
[WEBSITE] An error has occured on path /:
Error: ENOENT: no such file or directory, open './themes/Qwakeactyl/index.ejs'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync [as fileLoader] (node:fs:453:35)
    at fileLoader (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:293:18)
    at handleCache (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:233:16)
    at tryHandleCache (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:274:16)
    at Object.exports.renderFile (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:491:10)
    at C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\api\pages.js:72:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './themes/Qwakeactyl/index.ejs'
}
[WEBSITE] An error has occured on path /favicon.ico:
Error: ENOENT: no such file or directory, open './themes/Qwakeactyl/index.ejs'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync [as fileLoader] (node:fs:453:35)
    at fileLoader (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:293:18)
    at handleCache (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:233:16)
    at tryHandleCache (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:274:16)
    at Object.exports.renderFile (C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\node_modules\ejs\lib\ejs.js:491:10)
    at C:\Users\david\Desktop\Qwakeactyl-Qwakeactyl-2.0.1\index.js:306:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './themes/Qwakeactyl/index.ejs'
}

**Comment by IndianDevInc** [comment]
./themes/Qwakeactyl/index.ejs is issue that the theme folder need to be as themes
